[build]
builder = "nixpacks"

[deploy]
startCommand = "php -r \"file_exists('database/database.sqlite') || touch('database/database.sqlite');\" && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"
healthcheckPath = "/up"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
